# Generated by Django 3.2.6 on 2022-05-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='assign',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='thesis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patents',
            name='assign',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patents',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patents',
            name='num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patents',
            name='title',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
