# Generated by Django 3.2.6 on 2022-03-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domestic_Paper',
            fields=[
                ('title', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20, null=True)),
                ('paper_link', models.CharField(max_length=30, null=True)),
                ('thesis', models.CharField(max_length=20, null=True)),
                ('assign', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Int_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], default='2022', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='International_Paper',
            fields=[
                ('title', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20, null=True)),
                ('paper_link', models.CharField(max_length=30, null=True)),
                ('thesis', models.CharField(max_length=20, null=True)),
                ('assign', models.CharField(max_length=20, null=True)),
                ('year', models.ManyToManyField(blank=True, related_name='international', to='publication.Int_Year')),
            ],
        ),
        migrations.RenameModel(
            old_name='Pub_Year',
            new_name='Dom_Year',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.AddField(
            model_name='domestic_paper',
            name='year',
            field=models.ManyToManyField(blank=True, related_name='domestic', to='publication.Dom_Year'),
        ),
    ]
