# Generated by Django 3.2.6 on 2023-01-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lecture', models.ManyToManyField(to='photo.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('title', 'date')},
            },
        ),
    ]
