# Generated by Django 3.2.6 on 2022-07-07 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('title', 'date')},
        ),
    ]
