# Generated by Django 3.2.6 on 2023-01-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('speaker', models.CharField(max_length=50, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('year', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('slide', models.CharField(max_length=100, null=True)),
                ('paper', models.CharField(max_length=100, null=True)),
            ],
            options={
                'unique_together': {('title', 'date')},
            },
        ),
    ]
