# Generated by Django 3.2.6 on 2022-02-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dissertation',
            new_name='Thesis',
        ),
        migrations.RemoveField(
            model_name='master',
            name='dissertation',
        ),
        migrations.AddField(
            model_name='master',
            name='thesis',
            field=models.ManyToManyField(blank=True, related_name='master', to='member.Thesis'),
        ),
    ]
