# Generated by Django 3.2.6 on 2022-05-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='employment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
